FROM node:22-alpine

WORKDIR /app

COPY package.json package-lock.json ./

RUN npm ci

COPY prisma ./prisma
COPY prisma.config.ts ./

CMD ["sh", "-c", "npx prisma generate && npx prisma migrate deploy && npx prisma db seed"]